/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://o3zanq4345gfngzf3q42jgexwu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fvr7ruwicffydhy2g7ihcmazcy",
    "aws_cognito_identity_pool_id": "eu-central-1:63653dcf-9588-4ebf-8d8e-434ffc2ccf73",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_QBj8aYmNx",
    "aws_user_pools_web_client_id": "ej6mohbrgd4prbso71c1por37",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
